CREATE TABLE upcoming_appts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    appt_date DATE NOT NULL,
    appt_time TIME NOT NULL,
    appt_doctor TEXT NOT NULL,
    appt_location TEXT NOT NULL, 
    appt_purpose TEXT NOT NULL,
    appt_notes TEXT,
    copay numeric,
    doc_bill numeric,
    insurance_bill numeric,
    upcoming_appt BOOLEAN NOT NULL
);

